apiVersion: v1
kind: Service
metadata:
  name: portfolio-frontend-service
  labels:
    app: portfolio-frontend
spec:
  type: NodePort
  selector:
    app: portfolio-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30082
